version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - dependencies
      - area: ci
    commit-message:
      prefix: "ci"

  - package-ecosystem: npm
    directory: "/mesher/landing"
    schedule:
      interval: weekly
    labels:
      - dependencies
      - area: landing
    commit-message:
      prefix: "landing"

  - package-ecosystem: npm
    directory: "/mesher/client"
    schedule:
      interval: weekly
    labels:
      - dependencies
      - area: client
    commit-message:
      prefix: "client"
