version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - dependencies
      - area: ci
    commit-message:
      prefix: "ci"

  - package-ecosystem: npm
    directory: "/mesher/landing"
    schedule:
      interval: weekly
    labels:
      - dependencies
      - area: landing
    commit-message:
      prefix: "landing"

  - package-ecosystem: npm
    directory: "/mesher/frontend-exp"
    schedule:
      interval: weekly
    labels:
      - dependencies
      - area: frontend-exp
    commit-message:
      prefix: "frontend-exp"
