/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as SplatRouteImport } from './routes/$'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard.index'
import { Route as DashboardTreasuryRouteImport } from './routes/_dashboard.treasury'
import { Route as DashboardSolanaProgramsRouteImport } from './routes/_dashboard.solana-programs'
import { Route as DashboardSettingsRouteImport } from './routes/_dashboard.settings'
import { Route as DashboardReleasesRouteImport } from './routes/_dashboard.releases'
import { Route as DashboardPerformanceRouteImport } from './routes/_dashboard.performance'
import { Route as DashboardBountiesRouteImport } from './routes/_dashboard.bounties'
import { Route as DashboardAlertsRouteImport } from './routes/_dashboard.alerts'

const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTreasuryRoute = DashboardTreasuryRouteImport.update({
  id: '/treasury',
  path: '/treasury',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSolanaProgramsRoute = DashboardSolanaProgramsRouteImport.update({
  id: '/solana-programs',
  path: '/solana-programs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReleasesRoute = DashboardReleasesRouteImport.update({
  id: '/releases',
  path: '/releases',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPerformanceRoute = DashboardPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBountiesRoute = DashboardBountiesRouteImport.update({
  id: '/bounties',
  path: '/bounties',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAlertsRoute = DashboardAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/': typeof DashboardIndexRoute
  '/alerts': typeof DashboardAlertsRoute
  '/bounties': typeof DashboardBountiesRoute
  '/performance': typeof DashboardPerformanceRoute
  '/releases': typeof DashboardReleasesRoute
  '/settings': typeof DashboardSettingsRoute
  '/solana-programs': typeof DashboardSolanaProgramsRoute
  '/treasury': typeof DashboardTreasuryRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/alerts': typeof DashboardAlertsRoute
  '/bounties': typeof DashboardBountiesRoute
  '/performance': typeof DashboardPerformanceRoute
  '/releases': typeof DashboardReleasesRoute
  '/settings': typeof DashboardSettingsRoute
  '/solana-programs': typeof DashboardSolanaProgramsRoute
  '/treasury': typeof DashboardTreasuryRoute
  '/': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$': typeof SplatRoute
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_dashboard/alerts': typeof DashboardAlertsRoute
  '/_dashboard/bounties': typeof DashboardBountiesRoute
  '/_dashboard/performance': typeof DashboardPerformanceRoute
  '/_dashboard/releases': typeof DashboardReleasesRoute
  '/_dashboard/settings': typeof DashboardSettingsRoute
  '/_dashboard/solana-programs': typeof DashboardSolanaProgramsRoute
  '/_dashboard/treasury': typeof DashboardTreasuryRoute
  '/_dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$'
    | '/'
    | '/alerts'
    | '/bounties'
    | '/performance'
    | '/releases'
    | '/settings'
    | '/solana-programs'
    | '/treasury'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/alerts'
    | '/bounties'
    | '/performance'
    | '/releases'
    | '/settings'
    | '/solana-programs'
    | '/treasury'
    | '/'
  id:
    | '__root__'
    | '/$'
    | '/_dashboard'
    | '/_dashboard/alerts'
    | '/_dashboard/bounties'
    | '/_dashboard/performance'
    | '/_dashboard/releases'
    | '/_dashboard/settings'
    | '/_dashboard/solana-programs'
    | '/_dashboard/treasury'
    | '/_dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SplatRoute: typeof SplatRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/treasury': {
      id: '/_dashboard/treasury'
      path: '/treasury'
      fullPath: '/treasury'
      preLoaderRoute: typeof DashboardTreasuryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/solana-programs': {
      id: '/_dashboard/solana-programs'
      path: '/solana-programs'
      fullPath: '/solana-programs'
      preLoaderRoute: typeof DashboardSolanaProgramsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings': {
      id: '/_dashboard/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/releases': {
      id: '/_dashboard/releases'
      path: '/releases'
      fullPath: '/releases'
      preLoaderRoute: typeof DashboardReleasesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/performance': {
      id: '/_dashboard/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof DashboardPerformanceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/bounties': {
      id: '/_dashboard/bounties'
      path: '/bounties'
      fullPath: '/bounties'
      preLoaderRoute: typeof DashboardBountiesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/alerts': {
      id: '/_dashboard/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof DashboardAlertsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAlertsRoute: typeof DashboardAlertsRoute
  DashboardBountiesRoute: typeof DashboardBountiesRoute
  DashboardPerformanceRoute: typeof DashboardPerformanceRoute
  DashboardReleasesRoute: typeof DashboardReleasesRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSolanaProgramsRoute: typeof DashboardSolanaProgramsRoute
  DashboardTreasuryRoute: typeof DashboardTreasuryRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAlertsRoute: DashboardAlertsRoute,
  DashboardBountiesRoute: DashboardBountiesRoute,
  DashboardPerformanceRoute: DashboardPerformanceRoute,
  DashboardReleasesRoute: DashboardReleasesRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSolanaProgramsRoute: DashboardSolanaProgramsRoute,
  DashboardTreasuryRoute: DashboardTreasuryRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SplatRoute: SplatRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
